from __future__ import annotations

import json
from dataclasses import dataclass, fields
from pathlib import Path
from typing import Any, TypeVar


@dataclass(frozen=True)
class DataConfig:
    symbol: str = "BTCUSDT"
    timeframe: str = "1m"
    path: str = "data/sample_btcusdt_1m.csv"


@dataclass(frozen=True)
class StrategyConfig:
    fast_ema: int = 9
    slow_ema: int = 21
    atr_period: int = 14
    channel_period: int = 20
    min_atr_pct: float = 0.00035
    max_atr_pct: float = 0.01
    breakout_buffer_atr: float = 0.0
    ema_gap_atr: float = 0.0
    volume_period: int = 20
    min_volume_ratio: float = 0.0
    stop_loss_atr: float = 1.2
    take_profit_atr: float = 1.8
    breakeven_atr: float = 0.0
    trailing_activation_atr: float = 1.0
    trailing_stop_atr: float = 0.0
    max_holding_bars: int = 0
    spike_guard_enabled: bool = True
    spike_min_range_atr: float = 3.0
    spike_min_wick_atr: float = 1.4
    spike_min_wick_ratio: float = 0.55
    spike_min_volume_ratio: float = 1.2
    spike_block_bars: int = 3
    spike_trade_enabled: bool = True
    spike_recovery_ratio: float = 0.45
    spike_stop_atr: float = 0.7
    spike_take_profit_atr: float = 0.9
    spike_risk_multiplier: float = 0.35
    spike_max_holding_bars: int = 6
    rsi_reversal_enabled: bool = True
    allow_short: bool = True
    long_score_threshold: float = 0.25
    short_score_threshold: float = 0.25
    long_risk_bias: float = 1.0
    short_risk_bias: float = 1.0
    regime_filter_enabled: bool = False
    regime_lookback: int = 24
    long_min_slow_slope_atr: float = -1.0
    short_max_slow_slope_atr: float = 1.0
    super_volume_breakout_enabled: bool = True
    super_volume_min_ratio: float = 3.0
    super_volume_min_breakout_atr: float = 0.75
    super_volume_min_body_atr: float = 0.35
    super_volume_confidence_boost: float = 0.15
    super_volume_risk_multiplier: float = 1.35
    super_volume_take_profit_multiplier: float = 1.35
    super_volume_live_chase_guard_enabled: bool = False
    super_volume_max_entry_chase_pct: float = 0.006
    super_volume_max_holding_bars: int = 0
    entry_timing_filter_enabled: bool = False
    entry_timing_timeframe: str = "15m"
    entry_timing_rsi_fast_period: int = 6
    entry_timing_rsi_mid_period: int = 12
    entry_timing_long_rsi_fast_ceiling: float = 82.0
    entry_timing_long_rsi_mid_ceiling: float = 76.0
    entry_timing_short_rsi_fast_floor: float = 18.0
    entry_timing_short_rsi_mid_floor: float = 24.0
    entry_timing_max_chase_pct: float = 0.010
    entry_timing_reversal_pct: float = 0.006
    entry_execution_filter_enabled: bool = False
    entry_execution_filter_trend_only: bool = True
    entry_execution_timeframe: str = "5m"
    entry_execution_rsi_fast_period: int = 6
    entry_execution_rsi_mid_period: int = 12
    entry_execution_long_rsi_fast_ceiling: float = 84.0
    entry_execution_long_rsi_mid_ceiling: float = 78.0
    entry_execution_short_rsi_fast_floor: float = 16.0
    entry_execution_short_rsi_mid_floor: float = 22.0
    entry_execution_max_chase_pct: float = 0.004
    entry_execution_reversal_pct: float = 0.003
    entry_execution_max_adverse_wick_pct: float = 0.55
    ordinary_breakout_enabled: bool = True
    ordinary_breakout_min_rank_score: float = 0.0
    ordinary_breakout_risk_multiplier: float = 1.0
    pullback_reclaim_enabled: bool = True
    fast_breakout_enabled: bool = False
    fast_breakout_timeframe: str = "5m"
    fast_breakout_channel_period: int = 18
    fast_breakout_volume_period: int = 24
    fast_breakout_min_volume_ratio: float = 2.5
    fast_breakout_min_breakout_atr: float = 0.30
    fast_breakout_min_body_atr: float = 0.35
    fast_breakout_risk_multiplier: float = 0.55
    fast_breakout_take_profit_atr: float = 1.10
    fast_breakout_stop_loss_atr: float = 0.85
    fast_breakout_max_holding_bars: int = 2
    fast_breakout_long_rsi_fast_ceiling: float = 86.0
    fast_breakout_long_rsi_mid_ceiling: float = 80.0
    fast_breakout_short_rsi_fast_floor: float = 14.0
    fast_breakout_short_rsi_mid_floor: float = 20.0
    fast_breakout_max_adverse_wick_pct: float = 0.50
    trend_reference_filter_enabled: bool = False
    trend_reference_timeframe: str = "1h"
    trend_reference_lookback_bars: int = 6
    trend_reference_buffer_atr: float = 0.08
    trend_reference_slope_atr: float = 0.04
    trend_reference_super_volume_risk_multiplier: float = 0.60
    breakout_rsi_guard_enabled: bool = False
    breakout_rsi_fast_period: int = 6
    breakout_rsi_mid_period: int = 12
    breakout_long_rsi_fast_ceiling: float = 85.0
    breakout_long_rsi_mid_ceiling: float = 74.0
    breakout_short_rsi_fast_floor: float = 15.0
    breakout_short_rsi_mid_floor: float = 26.0
    startup_breakout_enabled: bool = False
    startup_min_volume_ratio: float = 2.0
    startup_min_breakout_atr: float = 0.0
    startup_min_body_atr: float = 0.65
    startup_risk_multiplier: float = 0.85
    startup_take_profit_multiplier: float = 1.2
    trend_risk_control_enabled: bool = False
    trend_risk_min_holding_bars: int = 18
    trend_long_risk_multiplier: float = 1.0
    trend_short_risk_multiplier: float = 1.0
    trend_super_volume_min_risk_multiplier: float = 0.85
    trend_loss_guard_enabled: bool = False
    trend_loss_guard_bars: int = 3
    trend_loss_guard_loss_pct: float = 0.006
    trend_loss_guard_super_volume_bars: int = 5
    trend_loss_guard_super_volume_loss_pct: float = 0.009
    account_loss_guard_enabled: bool = False
    account_loss_guard_pct: float = 0.012
    account_loss_guard_min_bars: int = 1
    stale_position_exit_enabled: bool = False
    stale_observation_bars: int = 8
    stale_force_exit_bars: int = 12
    stale_super_volume_observation_bars: int = 3
    stale_super_volume_force_exit_bars: int = 6
    indicator_trend_guard_enabled: bool = False
    indicator_trend_guard_lookback_bars: int = 12
    indicator_trend_guard_buffer_atr: float = 0.10
    indicator_trend_guard_slope_atr: float = 0.0
    indicator_max_holding_bars: int = 8
    indicator_confirmed_cross_extreme_guard_enabled: bool = False
    indicator_confirmed_extreme_lookback_bars: int = 4
    indicator_confirmed_long_max_rsi: float = 42.0
    indicator_confirmed_long_max_kdj: float = 35.0
    indicator_confirmed_short_min_rsi: float = 58.0
    indicator_confirmed_short_min_kdj: float = 65.0
    indicator_confirmed_trend_fallback_enabled: bool = True
    indicator_confirmed_trend_buffer_atr: float = 0.15
    indicator_confirmed_trend_slope_atr: float = 0.05
    indicator_confirmed_cross_extreme_required_enabled: bool = False
    indicator_confirmed_cross_long_max_rsi: float = 45.0
    indicator_confirmed_cross_long_max_kdj: float = 35.0
    indicator_confirmed_cross_short_min_rsi: float = 60.0
    indicator_confirmed_cross_short_min_kdj: float = 70.0
    indicator_reference_guard_enabled: bool = False
    indicator_reference_guard_long_enabled: bool = True
    indicator_reference_guard_short_enabled: bool = True
    indicator_reference_timeframe: str = "1h"
    indicator_reference_lookback_bars: int = 12
    indicator_reference_buffer_atr: float = 0.10
    indicator_reference_slope_atr: float = 0.05
    indicator_reference_extreme_override_enabled: bool = True
    indicator_reference_long_extreme_rsi: float = 38.0
    indicator_reference_long_extreme_kdj: float = 30.0
    indicator_reference_short_extreme_rsi: float = 62.0
    indicator_reference_short_extreme_kdj: float = 70.0
    indicator_reversal_size_multiplier: float = 1.0
    indicator_long_size_multiplier: float = 0.0
    indicator_short_size_multiplier: float = 0.0
    indicator_long_stop_loss_atr: float = 0.0
    indicator_short_stop_loss_atr: float = 0.0
    indicator_long_take_profit_atr: float = 0.0
    indicator_short_take_profit_atr: float = 0.0
    indicator_long_max_holding_bars: int = 0
    indicator_short_max_holding_bars: int = 0
    indicator_long_confirmed_cross_risk_multiplier: float = 0.0
    indicator_short_confirmed_cross_risk_multiplier: float = 0.0
    indicator_long_pre_cross_risk_multiplier: float = 0.0
    indicator_short_pre_cross_risk_multiplier: float = 0.0
    indicator_reversal_loss_pause_enabled: bool = False
    indicator_reversal_loss_pause_losses: int = 2
    indicator_reversal_loss_pause_bars: int = 8
    indicator_min_rank_guard_enabled: bool = False
    indicator_min_rank_score: float = 3.0
    btc_market_filter_enabled: bool = False
    btc_market_symbol: str = "BTCUSDT"
    btc_market_timeframe: str = "30m"
    btc_market_lookback_bars: int = 12
    btc_market_confirmation_enabled: bool = False
    btc_market_confirmation_timeframe: str = "8h"
    btc_market_confirmation_lookback_bars: int = 2
    btc_market_ema_period: int = 21
    btc_market_filter_trend_only: bool = True
    btc_market_filter_min_holding_bars: int = 18
    btc_bull_return_threshold: float = 0.006
    btc_bear_return_threshold: float = -0.006
    btc_market_slope_atr_threshold: float = 0.20
    btc_counter_trend_super_volume_only: bool = True
    btc_counter_trend_min_rank_score: float = 6.2
    btc_counter_trend_min_momentum_pct: float = 0.025
    btc_counter_trend_min_volume_ratio: float = 2.2
    btc_counter_trend_risk_multiplier: float = 0.45
    weak_market_long_filter_enabled: bool = False
    weak_market_lookback_bars: int = 48
    weak_market_breadth_threshold: float = 0.42
    weak_market_avg_return_threshold: float = -0.012
    weak_market_long_super_volume_only: bool = True
    weak_market_long_min_rank_score: float = 4.8
    weak_market_long_risk_multiplier: float = 0.55
    strong_market_short_filter_enabled: bool = False
    strong_market_lookback_bars: int = 12
    strong_market_breadth_threshold: float = 0.58
    strong_market_avg_return_threshold: float = 0.006
    strong_market_short_min_rank_score: float = 6.2
    strong_market_short_risk_multiplier: float = 0.45
    oi_flush_reversal_enabled: bool = True
    oi_flush_price_drop_min_pct: float = 0.008
    oi_flush_price_drop_atr_mult: float = 2.0
    oi_flush_oi_drop_15m: float = -0.025
    oi_flush_sell_imbalance_15m: float = 0.62
    oi_flush_sell_exhaustion_5m: float = 0.55
    oi_flush_btc_min_ret_15m: float = -0.008
    oi_flush_max_funding_rate: float = 0.0002
    oi_flush_pending_bars: int = 10
    oi_flush_reclaim_ema_period: int = 9
    oi_flush_min_close_position: float = 0.60
    oi_flush_max_stop_pct: float = 0.012
    oi_flush_stop_atr_mult: float = 0.8
    oi_flush_take_profit_r: float = 1.7
    oi_flush_time_stop_minutes: int = 30
    oi_flush_fail_fast_minutes: int = 8
    oi_flush_fail_fast_min_r: float = 0.4
    oi_flush_max_daily_trades: int = 2
    oi_flush_symbol_cooldown_hours: int = 6
    oi_flush_risk_multiplier: float = 0.40
    mtf_4h_rsi_regime_enabled: bool = False
    mtf_allow_long: bool = True
    mtf_allow_short: bool = True
    mtf_symbols_mode: str = "top30"
    mtf_disable_legacy_strategies: bool = False
    mtf_regime_timeframe: str = "4h"
    mtf_trigger_timeframe: str = "15m"
    mtf_secondary_2h_enabled: bool = False
    mtf_4h_rsi_period: int = 14
    mtf_4h_rsi_lookback_bars: int = 8
    mtf_4h_long_rsi_oversold: float = 34.0
    mtf_4h_long_rsi_reclaim: float = 38.0
    mtf_4h_short_rsi_overbought: float = 66.0
    mtf_4h_short_rsi_reject: float = 62.0
    mtf_4h_ema_fast: int = 9
    mtf_4h_ema_mid: int = 21
    mtf_4h_require_macd_hist_turn: bool = True
    mtf_4h_require_divergence: bool = False
    mtf_4h_max_distance_from_ema21_pct: float = 0.035
    mtf_2h_rsi_period: int = 14
    mtf_2h_rsi_lookback_bars: int = 10
    mtf_2h_long_rsi_oversold: float = 36.0
    mtf_2h_long_rsi_reclaim: float = 40.0
    mtf_2h_short_rsi_overbought: float = 64.0
    mtf_2h_short_rsi_reject: float = 60.0
    mtf_2h_ema_fast: int = 9
    mtf_2h_ema_mid: int = 21
    mtf_2h_require_macd_hist_turn: bool = True
    mtf_2h_require_divergence: bool = False
    mtf_2h_max_distance_from_ema21_pct: float = 0.045
    mtf_1h_ema_period: int = 21
    mtf_1h_long_min_rsi: float = 45.0
    mtf_1h_short_max_rsi: float = 55.0
    mtf_1h_strict_long_min_rsi: float = 50.0
    mtf_1h_strict_short_max_rsi: float = 50.0
    mtf_1h_swing_lookback: int = 3
    mtf_30m_ema_period: int = 21
    mtf_30m_alt_ema_period: int = 34
    mtf_30m_rsi_min: float = 42.0
    mtf_30m_rsi_max: float = 58.0
    mtf_30m_max_distance_from_ema_pct: float = 0.008
    mtf_30m_swing_lookback: int = 6
    mtf_15m_trigger_mode: str = "sweep"
    mtf_15m_min_close_position_long: float = 0.60
    mtf_15m_max_close_position_short: float = 0.40
    mtf_15m_structure_break_lookback: int = 3
    mtf_15m_max_distance_from_30m_ema_pct: float = 0.010
    mtf_15m_max_body_atr: float = 1.8
    mtf_trigger_volume_filter_enabled: bool = False
    mtf_trigger_volume_period: int = 20
    mtf_trigger_min_volume_ratio: float = 1.20
    mtf_use_funding_filter: bool = True
    mtf_min_entry_price: float = 2.0
    mtf_long_min_funding_rate: float = 0.0
    mtf_long_max_funding_rate: float = 0.0002
    mtf_short_min_funding_rate: float = -0.0002
    mtf_short_max_funding_rate: float = 1.0
    mtf_use_oi_filter: bool = True
    mtf_oi_30m_max_increase_pct: float = 0.0
    mtf_btc_1h_long_min_return_pct: float = -0.006
    mtf_btc_1h_short_max_return_pct: float = 0.006
    mtf_btc_4h_block_strong_opposite: bool = True
    mtf_max_stop_pct: float = 0.020
    mtf_stop_atr15m_mult: float = 0.25
    mtf_take_profit_r: float = 2.0
    mtf_risk_multiplier: float = 0.55
    mtf_symbol_margin_pct: float = 0.0
    mtf_account_margin_usage_pct: float = 0.0
    mtf_move_stop_to_breakeven_r: float = 1.0
    mtf_trailing_start_r: float = 1.5
    mtf_trailing_atr15m_mult: float = 1.0
    mtf_fail_fast_minutes: int = 90
    mtf_fail_fast_min_r: float = 0.5
    mtf_max_holding_minutes: int = 720
    mtf_max_daily_trades: int = 2
    mtf_max_open_positions: int = 1
    mtf_symbol_cooldown_hours: int = 12
    mtf_daily_loss_stop_trades: int = 2
    mtf_oi_data_dir: str = "data/binance_oi_taker_5m"
    mtf_funding_data_dir: str = "data/binance_oi_flush_funding"


@dataclass(frozen=True)
class RiskConfig:
    initial_equity: float = 10_000.0
    fee_bps: float = 4.0
    slippage_bps: float = 2.0
    max_leverage: float = 2.0
    risk_per_trade_pct: float = 0.005
    max_position_notional_pct: float = 1.0
    max_daily_loss_pct: float = 0.03
    max_drawdown_pct: float = 0.15
    maintenance_margin_pct: float = 0.005
    min_order_notional: float = 10.0
    cooldown_bars_after_loss: int = 5
    initial_entry_fraction: float = 0.75
    scale_in_enabled: bool = True
    scale_in_fraction: float = 0.25
    scale_in_profit_trigger_pct: float = 0.004
    scale_in_min_score: float = 0.55
    max_scale_ins: int = 1
    loss_scale_in_enabled: bool = False


@dataclass(frozen=True)
class AppConfig:
    data: DataConfig
    strategy: StrategyConfig
    risk: RiskConfig


T = TypeVar("T")


def _coerce_dataclass(cls: type[T], values: dict[str, Any]) -> T:
    allowed = {field.name for field in fields(cls)}
    unknown = sorted(set(values) - allowed)
    if unknown:
        raise ValueError(f"unknown config keys for {cls.__name__}: {', '.join(unknown)}")
    return cls(**values)


def load_config(path: str | Path) -> AppConfig:
    raw = json.loads(Path(path).read_text(encoding="utf-8"))
    return AppConfig(
        data=_coerce_dataclass(DataConfig, raw.get("data", {})),
        strategy=_coerce_dataclass(StrategyConfig, raw.get("strategy", {})),
        risk=_coerce_dataclass(RiskConfig, raw.get("risk", {})),
    )
